config/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('weblog.urls')),
]

weblog/urls.py
from django.urls import path
from .views import WeblogView
urlpatterns = [
    path('', WeblogView.as_view() ,name='weblog')
]

weblog/models.py
from django.db import models

# Create your models here.

class Weblog(models.Model):
    weblog = models.CharField(max_length=225)

    def __str__(self) -> str:
        return self.weblog

weblog/views.py
#from django.shortcuts import render
#from django.http import HttpResponse
#from django.views import View
from .models import Weblog
from django.views.generic import TemplateView
from django.views.generic import ListView
#def weblog(request):
#    return render(request, 'home.html')

class WeblogView(TemplateView):
    template_name='home.html'
    #def get(self, request):
    #    return render(request, 'home.html')
class WeblogView(ListView):
    model =Weblog
    template_name='home.html'

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>alireza webstore</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body>
    <header>
        <nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
            <div class="container-fluid">
              <a class="navbar-brand" href="#">Navbar</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarColor01">
                <ul class="navbar-nav me-auto">
                  <li class="nav-item">
                    <a class="nav-link active" href="#">Home
                      <span class="visually-hidden">(current)</span>
                    </a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#">Features</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#">Pricing</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#">About</a>
                  </li>
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Dropdown</a>
                    <div class="dropdown-menu">
                      <a class="dropdown-item" href="#">Action</a>
                      <a class="dropdown-item" href="#">Another action</a>
                      <a class="dropdown-item" href="#">Something else here</a>
                      <div class="dropdown-divider"></div>
                      <a class="dropdown-item" href="#">Separated link</a>
                    </div>
                  </li>
                </ul>
                <form class="d-flex">
                  <input class="form-control me-sm-2" type="search" placeholder="Search">
                  <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
                </form>
              </div>
            </div>
          </nav>
    </header>
    <div class="container">
        {% block content%}
        {% endblock content %}

    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block content %}
    <h1> weblog alireza</h1>
    <div class="list-group">
        {% for weblog in weblog_list %}
            <a href="#" class="list-group-item list-group-item-action"> {{ weblog.weblog}} </a>
        {% endfor %}

    </div>
{% endblock content %}

templates/home11.html
<!DOCTYPE html>
<html  lang="fa">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>قالب صفحه در دست ساخت :: دریافت شده از Webrubik.com</title>
	<!-- font-awesome -->
	<link href="fonts/font-awesome/css/font-awesome.min.css" rel="stylesheet">
	<!-- Style CSS -->
	<link href="css/style.css" rel="stylesheet">
  </head>
  <body>
  	<section class="wraper">
  		<header class="header">
  			<h1>  django webstore  </h1>
  			<h2>  فروشگاه جنگو علیرضا  </h2>
  		</header>
  		<!-- .header -->
  		<section class="countdown-wrapper">
  			<ul id="back-countdiown">
  				<li>                    
  					<span class="seconds">30</span>
  					<p class="fnt">ثانیه</p>
  				</li>
  				<li>
  					<span class="minutes">30</span>
  					<p class="fnt">دقیقه </p>
  				</li>
  				<li>
  					<span class="hours">12</span>
  					<p class="fnt">ساعت</p>
  				</li>
  				<li>
  					<span class="days">30</span>
  					<p class="fnt">روز</p>
  				</li>               
  			</ul><!-- #back-countdiown -->
  		</section><!-- .countdown-wrapper -->
  		<section class="subscribe">
  			<form class="subscribe-form" role="form" method="">
  				<input type="email" class="form-control" id="exampleInputEmail1" placeholder="ایمیل خود را وارد کنید">
  				<input type="submit" value="من را خبر کن" class="form-control" >
  			</form>
  		</section><!-- .subscribe-->

  		<footer class="footer">
  			<section class="social-links">
  				<ul>
  					<li><a href="#"><i class="fa fa-facebook"></i></a></li>
  					<li><a href="#"><i class="fa fa-twitter"></i></a></li>
  					<li><a href="#"><i class="fa fa-dribbble"></i></a></li>
  					<li><a href="#"><i class="fa fa-google-plus"></i></a></li>
  					<li><a href="#"><i class="fa fa-pinterest"></i></a></li>
  				</ul>
  			</section><!-- /.social-links -->
  			<ul class="copyright">
  				<li dir="ltr">&copy; Proximity. All rights reserved.</li>
  				<li>Design By: <a href="http://uicookies.com">uiCookies</a></li>
			  </ul>
			  <ul class="copyright">
				<li>فارسی و راست چین شده توسط : <a href="http://webrubik.com">وب روبیک</a></li>
			</ul>
  		</footer>
  	</section>
  	<div class="fullscreen-bg">
  		<video loop muted autoplay poster="img/videoframe.jpg" class="fullscreen-bg__video">
  			<source src="img/video-bg.mp4" type="video/mp4">
  		</video>
  	</div> <!-- .fullscreen-bg -->
  	<!-- Script -->
  	<script src="js/jquery-2.1.4.min.js"></script>
  	<script src="js/coundown-timer.js"></script>
  	<script src="js/scripts.js"></script>
  	</body><!-- This template has been downloaded from Webrubik.com -->
</html>